### ISSUE TITLE
pip has old source code?

### ISSUE THREAD

**Issue by KCrux** [janezd/baycomp#14]
Hello,

I installed baycomp today with 'python -m pip install baycomp' and tried to use the 'two_on_multiple' function. 

Then I got the error message: 'ImportError: Hierarchical model requires 'pystan'; install it by 'pip install pystan''

According to the latest update of the source code this shoud be fixed already. But it seems like that this update wasn't posted to PyPI? On the website https://pypi.org/project/baycomp/#files the latest version is 1.0.2 from 2019 and this is the version i got with pip install, too.

Maybe you want to update this? :-)

**Comment by dpaetzel** [comment]
I think you're correct in that the latest updates haven't been posted to PyPI.

However, even with those latest updates you will get a similar error about `pystan` missing since that is an optional dependency (only the hierarchical model requires it) that you have to install by hand.

Note that you should be able to install the latest version from GitHub using

```
pip install git+https://github.com/janezd/baycomp.git
```

**Comment by KCrux** [comment]
Thank you for your fast answer.

I think I expressed myself a bit unfortunate. My point is that you get this error _after_ installing `pystan` ;-). It's fine that `pystan` is optional, but `baycomp` should worker after installing it.
